backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Page Content"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "data/content.json"
        fields:
          - { label: "Logo Image", name: "logo_image", widget: "image", required: false }
          - { label: "Logo Text", name: "logo_text", widget: "string", required: false }
          - { label: "Slideshow", name: "slideshow", widget: "list", fields: [
              { label: "Background Image", name: "background_image", widget: "image" },
              { label: "Headline", name: "headline", widget: "string" },
              { label: "Subheadline", name: "subheadline", widget: "string" },
              { label: "Button Text", name: "button_text", widget: "string" }
            ] }
          - { label: "Lineage Heading", name: "lineage_heading", widget: "string", default: "Our Lineage & Inspiration" }
          - { label: "Lineage Subheading", name: "lineage_subheading", widget: "string", default: "Guiding lights of our institution" }
          - { label: "Lineage Cards", name: "lineage_cards", widget: "list", fields: [
              { label: "Image", name: "image", widget: "image" },
              { label: "Name", name: "name", widget: "string" },
              { label: "Title", name: "title", widget: "string" },
              { label: "Description", name: "description", widget: "text" }
            ] }
          - { label: "Vision Heading", name: "vision_heading", widget: "string", default: "Our Vision" }
          - { label: "Vision Cards", name: "vision_cards", widget: "list", fields: [
              { label: "Icon", name: "icon", widget: "image" },
              { label: "Icon Background Color", name: "icon_bg_color", widget: "string", default: "#FFFBEB" },
              { label: "Text", name: "text", widget: "string" }
            ] }
          - { label: "About Us Heading", name: "about_us_heading", widget: "string", default: "About Us" }
          - { label: "About Us Description", name: "about_us_description", widget: "markdown", default: "We are dedicated to providing a balanced education that nurtures students both spiritually and materially. Our academic program follows the official NIOS (National Institute of Open Schooling) curriculum, ensuring a comprehensive and recognized educational foundation for all our students." }
          - { label: "Team Section Heading", name: "team_section_heading", widget: "string", default: "Our Dedicated Team" }
          - { label: "Team Members", name: "team_members", widget: "list", fields: [
              { label: "Name", name: "name", widget: "string" },
              { label: "Role", name: "role", widget: "string" }
            ] }
          - { label: "Gallery Heading", name: "gallery_heading", widget: "string", default: "Glimpses of Gurukula Life" }
          - { label: "Gallery Images", name: "gallery_images", widget: "list", fields: [
              { label: "Image", name: "image", widget: "image" }
            ] }
          - { label: "Donation Heading", name: "donation_heading", widget: "string", default: "Support Our Seva" }
          - { label: "Donation Options", name: "donation_options", widget: "list", fields: [
              { label: "Title", name: "title", widget: "string" },
              { label: "Type", name: "type", widget: "select", options: ["qr", "bank"] },
              { label: "QR Code Image", name: "qr_code", widget: "image", required: false },
              { label: "Description", name: "description", widget: "text" },
              { label: "Details", name: "details", widget: "list", required: false, fields: [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Value", name: "value", widget: "string" }
              ] }
            ] }
          - { label: "Footer Address", name: "footer_address", widget: "string" }
          - { label: "Email Address", name: "email_address", widget: "string" }
          - { label: "Contact Phone", name: "contact_phone", widget: "string" }
          - { label: "Copyright Note", name: "copyright_note", widget: "string" }
