backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "_data/content.json"
        fields:
          - {label: "SEO Title", name: "seo_title_home", widget: "string"}
          - {label: "SEO Description", name: "seo_description_home", widget: "string"}
          - {label: "Hero Image", name: "hero_image", widget: "image"}
          - {label: "Hero Headline", name: "hero_headline", widget: "string"}
          - {label: "Hero Subheadline", name: "hero_subheadline", widget: "string"}
      - label: "Projects Page"
        name: "projects_page"
        file: "_data/content.json"
        fields:
          - {label: "SEO Title", name: "seo_title_projects", widget: "string"}
          - {label: "SEO Description", name: "seo_description_projects", widget: "string"}
      - label: "About Page"
        name: "about_page"
        file: "_data/content.json"
        fields:
          - {label: "SEO Title", name: "seo_title_about", widget: "string"}
          - {label: "SEO Description", name: "seo_description_about", widget: "string"}
      - label: "Academics Page"
        name: "academics_page"
        file: "_data/content.json"
        fields:
          - {label: "SEO Title", name: "seo_title_academics", widget: "string"}
          - {label: "SEO Description", name: "seo_description_academics", widget: "string"}
          - {label: "Header Image", name: "academics_header_image", widget: "image"}
          - {label: "Spiritual Curriculum Title", name: "spiritual_curriculum_title", widget: "string"}
          - {label: "Spiritual Curriculum Text", name: "spiritual_curriculum_text", widget: "markdown"}
          - {label: "Academic Curriculum Title", name: "academic_curriculum_title", widget: "string"}
          - {label: "Academic Curriculum Text", name: "academic_curriculum_text", widget: "markdown"}
          - {label: "Practical Skills Title", name: "practical_skills_title", widget: "string"}
          - {label: "Practical Skills Text", name: "practical_skills_text", widget: "markdown"}
          - label: "Daily Schedule"
            name: "daily_schedule"
            widget: "list"
            summary: "{{fields.time}} - {{fields.activity}}"
            fields:
              - {label: "Time", name: "time", widget: "string"}
              - {label: "Activity", name: "activity", widget: "string"}
              - {label: "Icon", name: "icon", widget: "select", options: ["Sunrise", "BookOpen", "Book", "Utensils", "Wrench", "Play", "Users", "Bed"]}
      - label: "Admissions Page"
        name: "admissions_page"
        file: "_data/content.json"
        fields:
          - {label: "SEO Title", name: "seo_title_admissions", widget: "string"}
          - {label: "SEO Description", name: "seo_description_admissions", widget: "string"}
          - {label: "Header Image", name: "admissions_header_image", widget: "image"}
          - {label: "Intro Title", name: "admissions_intro_title", widget: "string"}
          - {label: "Intro Text", name: "admissions_intro_text", widget: "string"}
          - label: "FAQ"
            name: "faq"
            widget: "list"
            summary: "{{fields.question}}"
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "markdown"}
      - label: "Donate Page"
        name: "donate_page"
        file: "_data/content.json"
        fields:
          - {label: "SEO Title", name: "seo_title_donate", widget: "string"}
          - {label: "SEO Description", name: "seo_description_donate", widget: "string"}
          - {label: "Header Image", name: "donate_header_image", widget: "image"}
          - {label: "Intro Title", name: "donate_intro_title", widget: "string"}
          - {label: "Intro Text", name: "donate_intro_text", widget: "markdown"}
          - label: "Sponsor a Seva Options"
            name: "sponsor_options"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - {label: "Suggested Amount", name: "amount", widget: "string"}
              - {label: "Icon", name: "icon", widget: "select", options: ["Utensils", "Book", "UserCheck", "HeartHandshake"]}

