backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - file: "about.html"
        label: "About Us Page"
        name: "about"
        fields:
          # Adding 'required: false' allows you to publish even if these are empty
          - {label: "Rasanath Das Photo", name: "rasanath_img", widget: "image", required: false}
          - {label: "Sarvabhuta Dasi Photo", name: "sarvabhuta_img", widget: "image", required: false}
          - {label: "Prasad Barakade Photo", name: "prasad_img", widget: "image", required: false}
          - {label: "Harsh Sharma Photo", name: "harsh_img", widget: "image", required: false}

      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Srila Prabhupada Photo", name: "prabhupada_img", widget: "image", required: false}
          - {label: "Bhakti Raghava Swami Photo", name: "maharaj_img", widget: "image", required: false}
          - {label: "Gadadhar Das Photo", name: "gadadhar_img", widget: "image", required: false}

      - file: "donate.html"
        label: "Donate Page"
        name: "donate"
        fields:
          - {label: "UPI QR Code", name: "qr_code_img", widget: "image", required: false}
